name = "slink"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "."

# KV namespaces - Cloudflare Pages will create this automatically
[[kv_namespaces]]
binding = "SLINK_KV"
id = ""
preview_id = ""