name = "slink"
compatibility_date = "2024-01-01"

[build]
command = ""

[[kv_namespaces]]
binding = "SLINK_KV"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

[env.production]
[[env.production.kv_namespaces]]
binding = "SLINK_KV"
id = "your-production-kv-namespace-id-here"