name = "slink"
compatibility_date = "2024-01-01"

# Pages configuration
pages_build_output_dir = "."

# KV namespaces - Replace the IDs below with your actual KV namespace IDs
# Run: wrangler kv:namespace create "SLINK_KV" 
# Run: wrangler kv:namespace create "SLINK_KV" --preview
# Then replace the placeholder IDs below

# Uncomment and update the following lines with your actual KV namespace IDs:
# [[kv_namespaces]]
# binding = "SLINK_KV"
# id = "your-actual-kv-namespace-id"
# preview_id = "your-actual-preview-kv-namespace-id"